### ISSUE TITLE
Countdown Thing Improvements

### ISSUE THREAD

**Issue by My-Name-Is-Jeff** [Skytils/SkytilsMod#240]
Copy from Discord:

seconds keep going up
it doesn't know which second it ends so it keeps going up
https://imgur.com/8DnCAuy
Even if it has seconds:
https://imgur.com/7w1V85j

Put the text right next to the timer
like Starting in: 0d 7h 33m 35s (Monday, 01:35:00 CEST)
or just straight up 1:35:00 CEST
and orange would probably look better instead of that blue
looks out of place in skyblock menus

**Comment by RayDeeUx** [comment]
wait did we release countdown calculator to public? or is this just comments from other folks testing the feature

also i don't want to make the code more spaghetti than it is, so my plan is to calculate the countdown once and not do it anymore after that. hopefully that resolves the countdown seconds going up infinitely

as for placement and color of the timestamp:
the reason i chose cyan was because it's used very rarely in sb menu item lore tooltips, making it more distinctive among a sea of lore lines. I'll probably change it to color code `e` which is yellow (gold is often used for highlighting coins/enchantments) as a compromise.

placing it on a new line instead of appending it to the same line as the countdown is better for readability in the long run (imagine reading a timestamp that ended on a Thursday in November. now that's a hellishly long item lore line which makes for a very very wide tooltip).

anyways that's my immediate thoughts for the time being

**Comment by RayDeeUx** [comment]
yes there's a way to grab item timestamps for auctions but that's a double edged sword hence my spaghetti code concerns
