### ISSUE TITLE
Low health vignette blacks out screen

### ISSUE THREAD

**Issue by My-Name-Is-Jeff** [Skytils/SkytilsMod#349]
https://youtu.be/3WpKBdiqa2U

**Comment by TakoTheDev** [comment]
Decided to investigate this a bit:
- Can be replicated with only Patcher and Skytils
- Caused by HUD Caching
  - Also breaks [vanilla vignette](https://github.com/Sk1erLLC/Patcher/issues/165) which the feature is based on, but unlike the vanilla one it turns black instead of invisible
- Setting the `-Dmixin.debug=true` jvm argument fixes it for some reason

**Comment by TakoTheDev** [comment]
This got fixed by https://github.com/Skytils/SkytilsMod/commit/a5b406b9ab6a08e882cddc5f85e1007d2e8a7cf7 so shouldn't this be completed?

**Comment by My-Name-Is-Jeff** [comment]
Resolved by a5b406b9ab6a08e882cddc5f85e1007d2e8a7cf7
